aprendamais/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('registrar/', views.SignUp.as_view(), name='signup'),
]

aprendamais/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('contato/', views.ContactTemplateView.as_view(), name='contact')
]

aprendamais/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='index'),
    path('novo/', views.CourseCreateView.as_view(), name='create_course'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='detail_course'),
    #path('contato/', views.ContactTemplateView.as_view(), name='contact')
]

aprendamais/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aprendamais.core.urls')),
    path('conta/', include('aprendamais.accounts.urls')),
    path('conta/', include('django.contrib.auth.urls')),
    path('cursos/',include('aprendamais.courses.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aprendamais/accounts/models.py
from django.db import models

# Create your models here.

aprendamais/courses/models.py
from django.db import models

class Course(models.Model):

    name = models.CharField(
        'Nome',
        max_length=100
    )

    slug = models.SlugField(
        'Atalho'
    )

    about = models.TextField(
        'Sobre o curso',
        blank= True
    )

    description = models.TextField(
        'Descrição do curso',
        blank=True
    )

    start_date = models.DateField(
        'Data de Início',
        null=True,
        blank=True
    )

    image = models.FileField(
        upload_to='courses/images',
        verbose_name = 'Imagem',
        null = True,
        blank=True
    )

    created_at = models.DateTimeField(
        'Criado em',
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        'Atualizado em',
        auto_now=True
    )

    def save(self, *args, **kwargs):
        self.slug = self.name.replace(" ","")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Meta:
    verbose_name = 'Curso'
    verbose_name_plural = 'Cursos'
    ordering = ['name']

aprendamais/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactCourse (forms.Form):

    name = forms.CharField(label='Nome', max_length = 100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        subject = 'Contato sobre Curso %s' % course
        message  = 'Nome: %(name)s;Email: %(email)s;%(message)s'
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        message = message % context
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL] )

aprendamais/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'registration/signup.html'

aprendamais/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class HomeTemplateView(TemplateView):
    template_name='home.html'

class ContactTemplateView(TemplateView):
    template_name='contact.html'

aprendamais/courses/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import FormView
from .models import Course
from django.urls import reverse_lazy
from .forms import ContactCourse
from django.core.mail import send_mail
from django.conf import settings

class CourseListView(ListView):
    model = Course
    template_name = 'courses/index.html'

class CourseCreateView(CreateView):
    model = Course
    template_name = 'courses/create_course.html'
    fields = [
        'name',
        'description',
        'image',
    ]
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    success_url = reverse_lazy(
        viewname = 'courses:index',
    )

class CourseDetailView(DetailView, FormView):
    model = Course
    template_name = 'courses/course_detail.html'
    form_class = ContactCourse
    success_url = reverse_lazy(
        viewname = 'courses:index',
    )

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['form'] = ContactCourse
        return context

    def send_mail(self):
        subject = 'Contato sobre Curso %s' % 'test'
        message  = 'Nome: %(name)s;Email: %(email)s;%(message)s'
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        message = message % context
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL] )
    

aprendamais/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Aprenda Mais</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'imagens/Logo.png'%}"/>
</head>
<body>
<div class="content">
    <nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
        <a href="#" class="navbar-brand"><img src="{% static 'imagens/Logo.png'%}" alt="logo" style="width: 50px; height: 50px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                                <a class="nav-link action" href="{% url 'core:home' %}">Início<span class="sr-only">(current)</span></a>
                        </li>
                    <li class="nav-item">
                        <a href="{% url 'courses:index' %}" class="nav-link action">Cursos</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'core:contact' %}" class="nav-link action">Contato</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link action">Entrar</a>
                    </li>
                </ul>
        </div>
    </nav>

    <div class="main">
      {% block content %}{% endblock %}
    </div>

</div>

<footer class="page-footer font-small navbar-dark bg-dark pb-1">
        <!-- Copyright -->
        <div class="footer-copyright text-center" style="color: antiquewhite">© 2018 Copyright: <br>
          Aprenda+ - Uma simples plataforma de ensino a distância
        </div>
        <!-- Copyright -->
</footer>
</body>
</html>

aprendamais/core/templates/contact.html
{% extends "base.html" %}

{% block content%}

    <div class="container">
        <div class="row mt-5 mb-3">
            <div class="col"><h1>Fale Conosco</h1></div>
        </div>
        <div class="row">
            <p>Você pode entrar em cotato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        </div>
        <div class="row">
            <p class="font-weight-bold">Links:</p>
        </div>
        <div class="row">
            <ul>
                <li>Email: Jobs@gmail.com</li>
                <li>Facebook: Aprenda+cursos</li>
            </ul>
        </div>
    </div>
{% endblock %}

aprendamais/core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="alert alert-secondary" role="alert">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div>
                    <h1 class="font-weight-bold mb-3">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h3 class="font-weight-normal mb-5">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h3>
                    <p>
                        <a href="#" class="btn btn-dark">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="pt-3">
            <div class="row">
                <div class="col pt-3">
                    <div class="row">
                        <div class="col">
                                <h4>Vídeo-aulas e materiais digitais</h4>
                                <hr/>
                        </div>
                    </div>
                    <div class="row">
                         <div class="col"><h3 class="font-weight-bold">Publique suas aulas</h3></div>
                    </div>
                    <div class="row">
                            <div class="col">
                                    <p>
                                            O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                                    </p>
                            </div>
                    </div>
                </div>
                <div class="col">
                        <img src="http://placehold.it/400x250"
                                alt="Vídeo aulas e materiais digitais.">
                </div> 
            </div>
        </div>
        <div class="pt-3">
            <div class="row">
                <div class="col float-left">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
                <div class="col">
                    <div class="row mt-5">
                        <div class="col"> <h4>Fórum de Dúvidas</h4></div>
                        <hr>
                    </div>
                    <div class="row mt-3">
                        <div class="col"><h4 class="font-weight-bold">Interaja com seus alunos</h4></div>
                    </div> 
                    <div class="row">
                        <div class="col">
                                <p>
                                    No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                                </p>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
        <div class="pt-5 row">
            <div class="col">
                <div class="row">
                    <h4 class="mb-4">Exercícios</h4>
                    <hr>
                    <h3 class="font-weight-bold">Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="col">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
            </div>
            <div class="col pt-5">
                <div class="row"><h4 class="pb-3">Mural de Avisos</h4></div>
                <div class="row"><h4 class="font-weight-bold">Envie anúncios diretamente para os alunos</h3></div>
                <div class="row">
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}    

aprendamais/courses/templates/courses/course_detail.html
{% extends 'base.html'%}

{% load static %}

{% block content %}

<div class="alert alert-secondary" role="alert">
    <div class="row">
        <div class="col">
            <h1 class="display-3 font-weight-bold text-justify">{{ course.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2 style="word-wrap: break-word;">
                {{ course.description }}
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="col mt-3">
            <button class="btn btn-dark">Inscreva-se</button>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row mt-5">
        <div class="col">
            <div class="row">
                <div class="col">
                    <h4 class="font-weight-bold">Sobre o curso</h4>
                    <hr align="left" width="9%" >
                </div>
            </div>
            <div class="row">
                <div class="col text-justify">{{ course.about | linebreaks }}</div>
            </div>
        </div>
        <div class="col">
            <img width="300px" height="200px" 
            {% if course.image %}
                src="{{ course.image.url }}"
            {% else %}
                src="{% static "courses/imagens/default.jpg" %}"
            {% endif %} >
        </div>
    </div>
</div>

<hr>

<form action="" method="post">
    {% csrf_token %}
    <div class="form-group col-md-4 col-sm-4 col-xs-8">
        <label for="exampleInputEmail1">Endereço de email</label>
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
    </div>
    <div class="form-group col-md-4 col-sm-4 col-xs-8">
            <label for="name">Nome:</label>
            <input type="text" name="name" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Nome">
    </div>
    <div class="form-group col-md-4 col-sm-4 col-xs-8">
        <label for="Textarea">Mensagens/Pedidos</label>
        <textarea class="form-control" name="message" id="Textarea" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-dark">Enviar</button>
</form>

{% endblock %}

aprendamais/courses/templates/courses/create_course.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data"> <!-- multipart/form-data make upload the image in form-->
        {% csrf_token %}
        <div class="container mt-5">
            <div class="form-group">
                <label for="id_name">Nome</label>
                <input type="text" name="name"class="form-control" id="id_name" aria-describedby="name_course">
                <small id="name_course" class="form-text text-muted">Nome do curso</small>
            </div>
            <div class="form-group">
                <label for="description">Descrição do curso</label>
                <textarea class="form-control" name="description" rows="7" id="description" aria-describedby="desc"></textarea>
                <small id="desc" class="form-text text-muted">Descrição do curso</small>
            </div>
            <div class="form-group">
                <label for="description">Sobre o curso</label>
                <textarea class="form-control" name="about" rows="7" id="id_about" aria-describedby="aboutt"></textarea>
                <small id="aboutt" class="form-text text-muted">Ementa do curso</small>
            </div>
            <div class="form-group mb-5">
                <label for="id_image">Imagem</label>
                <input type="file" class="form-control-file" id="id_image">
            </div>
            <div class="form-group">
                <button class="btn btn-dark" type="submit">Enviar</button>
            </div>
        </div>
    </form>
{% endblock %}

aprendamais/courses/templates/courses/index.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

    <div class="container">
            <div class="row mt-3">
                    <div class="col text-center">
                            <h3 class="font-weight-bold"> Cursos oforecidos por nossa plataforma </h3>
                            <hr>
                    </div>
            </div>
                    {% for course in course_list %}
                      <div class="row border mt-3">
                          <div class="col mt-3 mb-3 ml-0">
                            <img width="300px" height="200px"
                                {% if course.image %}
                                    src="{{ course.image.url }}"
                                {% else %}
                                    src="{% static "courses/imagens/default.jpg" %}"
                                {% endif %} >
                          </div>
                          <div class="col">
                            <div class="row">
                                <div class="col">
                                  <font size="6"><a href="{% url 'courses:detail_course' course.slug %}" class="font-weight-bold">{{ course.name }}</a></font>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    {{ course.description | linebreaks}}
                                </div>
                            </div>
                          </div>
                      </div>

                        <!--
                        <div class="row">
                            <div class="border pl-2">
                                <div class="row">
                                    <div class="col mt-1 mb-1">
                                        <img width="300px" height="200px"
                                            {% if course.image %}
                                                src="{{ course.image.url }}"
                                            {% else %}
                                                src="{% static "courses/imagens/default.jpg" %}"
                                            {% endif %} >
                                    </div>
                                    <div class="col-sm">
                                        <div class="row">
                                            <div class="col">
                                                <a href="{% url 'courses:detail_course' course.slug %}" class="font-weight-bold">{{ course.name }}</a>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                {{ course.description | linebreaks}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                      -->
                    {% empty %}
                        <div class="row mt-3">
                            <div class="col text-center">
                                <h4> Não há cursos disponiveis </h4>
                            </div>
                        </div>
                    {% endfor %}
    </div>
{% endblock%}